services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: app
    init: true
    security_opt:
      - no-new-privileges:true
    environment:
      NODE_ENV: production
      PORT: 4001
    deploy:
      restart_policy:
        condition: always
        window: 120s
    networks:
      - pong-network
  waf:
    build:
      context: .
      dockerfile: ./waf/Dockerfile
    container_name: waf
    init: true
    security_opt:
      - no-new-privileges:true
    ports:
      - "8080:8080"
      - "8443:8443"
    deploy:
      restart_policy:
        condition: always
        window: 120s
    environment:
      BACKEND: http://app:4001
      PORT: 8080
      SSL_PORT: 8443
      NGINX_ALWAYS_TLS_REDIRECT: on
    # volumes:
    #   - ./waf/nginx/template/includes/:/etc/nginx/templates/includes/
    #   - ./waf/modsecurity/crs-setup.conf:/etc/modsecurity.d/crs-setup.conf
    #   - ./waf/modsecurity/modsecurity.conf:/etc/modsecurity.d/modsecurity.conf
    #   - ./waf/modsecurity/include.conf:/etc/modsecurity.d/include.conf
    #   - ./waf/modsecurity/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
    depends_on:
      - app
    networks:
      - pong-network

networks:
  pong-network:

volumes:
  db:
