services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: app
    init: true
    security_opt:
      - no-new-privileges:true
    ports:
      - "4001:4001"
    environment:
      NODE_ENV: production
      PORT: 4001
    deploy:
      restart_policy:
        condition: always
        window: 120s
    networks:
      - pong-network
  # frontend:
  #   build: frontend/.
  #   image: frontend
  #   container_name: frontend
  #   init: true
  #   security_opt:
  #     - no-new-privileges:true
  #   ports:
  #     - "80:80"
  #   deploy:
  #     restart_policy:
  #       condition: always
  #       window: 120s
  #   volumes:
  #     - ./frontend/src:/var/www/html/src
  #     - ./frontend/dist:/var/www/html/dist
  #   depends_on:
  #     - backend
  #   networks:
  #     - pong-network

networks:
  pong-network:

volumes:
  db:
