services:
  app:
    build:
      dockerfile: ./app/Dockerfile
    container_name: app
    init: true
    security_opt:
      - no-new-privileges:true
    environment:
      NODE_ENV: production
      PORT: 4001
    restart: always
    volumes:
      - db-data:/app/db
    networks:
      - pong-network
  waf:
    build:
      dockerfile: ./waf/Dockerfile
    container_name: waf
    init: true
    security_opt:
      - no-new-privileges:true
    secrets:
      - site_key
      - site_cert
    ports:
      - "8080:8080"
      - "8443:8443"
    restart: always
    environment:
      # nginx settings
      BACKEND: http://app:4001
      PORT: 8080
      SSL_PORT: 8443
      NGINX_ALWAYS_TLS_REDIRECT: on
      SSL_CERT: /etc/nginx/certs/fullchain.pem
      SSL_CERT_KEY: /etc/nginx/certs/key.pem
      # modsecurity settings
      MODSEC_RULE_ENGINE: On
      MODSEC_DEBUG_LOGLEVEL: 3 # errors, warnings, and notices
      # CRS settings
      BLOCKING_PARANOIA: 2
    volumes:
      - certs:/etc/nginx/certs:ro
    depends_on:
      - app
      - vault-agent
    networks:
      - pong-network
  vault:
    build:
      dockerfile: ./vault/Dockerfile
    container_name: vault
    init: true
    security_opt:
      - no-new-privileges:true
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    restart: always
    volumes:
      - vault-data:/vault/data
      - vault-secrets:/run/secrets
      - ./vault/config:/vault/config:ro
      - ./vault/policies:/vault/policies:ro
    depends_on:
      - app
      # - mysql
    networks:
      - pong-network
  vault-agent:
    image: hashicorp/vault:1.20.2
    container_name: vault-agent
    environment:
      VAULT_ADDR: "http://vault:8200"
    restart: always
    volumes:
      - ./vault-agent/config/agent.hcl:/vault/config/agent.hcl:ro
      - ./vault-agent/templates:/vault/templates:ro
      - vault-secrets:/vault/secrets
      - certs:/vault/certs
    command: agent -config=/vault/config/agent.hcl
    depends_on:
      - vault
    networks:
    - pong-network
  # mysql:
  #   image: mysql:8
  #   container_name: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpass
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - pong-network

networks:
  pong-network:

volumes:
  certs:
  db-data:
  vault-data:
  vault-secrets:

secrets:
  site_key:
    file: secrets/site.key
  site_cert:
    file: secrets/site.crt
