
services:
  backend:
    build: backend/.
    image: backend
    container_name: backend
    init: true
    security_opt:
      - no-new-privileges:true
    ports:
      - "4000:4000"
    deploy:
      restart_policy:
        condition: always
        window: 120s
    networks:
      - pong-network

  frontend-dev:
    build: frontend/.
    image: frontend-dev
    container_name: frontend-dev
    init: true
    security_opt:
      - no-new-privileges:true
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: always
        window: 120s
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - pong-network

networks:
  pong-network:
