services:
  app:
    build:
      dockerfile: ./app/Dockerfile
    container_name: app
    init: true
    security_opt:
      - no-new-privileges:true
    environment:
      NODE_ENV: production
      PORT: 4001
    restart: always
    volumes:
      - db-data:/app/db
    networks:
      - pong-network
  waf:
    build:
      dockerfile: ./waf/Dockerfile
    container_name: waf
    init: true
    security_opt:
      - no-new-privileges:true
    secrets:
      - site_key
      - site_cert
    ports:
      - "8080:8080"
      - "8443:8443"
    restart: always
    environment:
      # nginx settings
      BACKEND: http://app:4001
      PORT: 8080
      SSL_PORT: 8443
      NGINX_ALWAYS_TLS_REDIRECT: on
      SSL_CERT: /etc/nginx/conf/self-signed.crt
      SSL_CERT_KEY: /etc/nginx/conf/self-signed.key
      # modsecurity settings
      MODSEC_RULE_ENGINE: On
      MODSEC_DEBUG_LOGLEVEL: 3 # errors, warnings, and notices
      # CRS settings
      BLOCKING_PARANOIA: 2
    depends_on:
      - app
    networks:
      - pong-network
  vault:
    # build:
    #   context: .
    #   dockerfile: ./vault/Dockerfile
    image: hashicorp/vault:1.20.1
    container_name: vault
    init: true
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    restart: always
    volumes:
      - vault-data:/vault/data
      - ./vault/config:/vault/config
    command: vault server -config=/vault/config/vault.hcl
    depends_on:
      - app
      - mysql
    networks:
      - pong-network
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    networks:
      - pong-network

networks:
  pong-network:

volumes:
  db-data:
  vault-data:

secrets:
  site_key:
    file: secrets/site.key
  site_cert:
    file: secrets/site.crt
