services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: always
    command:
      - "http"
      - "--url"
      - "${DOMAIN_NAME}"
      - "--basic-auth"
      - "password:password"
      - "https://waf:${NGINX_SSL_PORT}"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      waf:
        condition: service_started
    networks:
      - pong-network
