services:
  app:
    build: ./app
    image: app
    container_name: app
    init: true
    security_opt:
      - no-new-privileges:true
    ports:
      - "4000:4000"
    deploy:
      restart_policy:
        condition: always
        window: 120s
    volumes:
      - type: volume
        source: db
        target: /app/db
    networks:
      - pong-network
  # frontend:
  #   build: frontend/.
  #   image: frontend
  #   container_name: frontend
  #   init: true
  #   security_opt:
  #     - no-new-privileges:true
  #   ports:
  #     - "80:80"
  #   deploy:
  #     restart_policy:
  #       condition: always
  #       window: 120s
  #   volumes:
  #     - ./frontend/src:/var/www/html/src
  #     - ./frontend/dist:/var/www/html/dist
  #   depends_on:
  #     - backend
  #   networks:
  #     - pong-network

networks:
  pong-network:


volumes:
  db:
