
services:
  backend:
    build: backend/.
    image: backend
    container_name: backend
    init: true
    security_opt:
      - no-new-privileges:true
    ports:
      - "4000:4000"
    deploy:
      restart_policy:
        condition: always
        window: 120s
    networks:
      - pong-network

  # database:
  #   build: database/.
  #   image: 
  #   container_name: database
  #   init: true
  #   security_opt:
  #     - no-new-privileges:true
  #   deploy:
  #     restart_policy:
  #       condition: always
  #       window: 120s
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - backend/data:/data
  #   networks:
  #     - pong-network

networks:
  pong-network:
